feat: Adding pivot point standard impls
amv-dev/yata pull request #37
Opened 2023-11-04 15:46 UTC by dandxy89

To implement this I needed to increase `IndicatorResult` result size to `12`. 

Resolves: https://github.com/amv-dev/yata/issues/36

2023-11-13 10:45 UTC, dandxy89 commented
@amv-dev - can you take a look at this and advise on changes?

2024-01-08 11:08 UTC, amv-dev commented
@dandxy89 Hello! Sorry for this looooooong anwer. I was having a lot of busy days...
I don't think it is good idea to increase size for `IndicatorResult`. The whole idea of fixed size for `IndicatorResult` was totally wrong and I already working on next version of the library, where this issue is handled correctly. 

But for now I'd recommend you to make you indicator as `Method`, not an `Indicator`. `Method` allows to define it's own `Output` type, where all the signals may be described.

2024-01-08 13:25 UTC, dandxy89 commented
No problem @amv-dev. 

Thats for the feedback - much appreciated.

Let me re-familiarise myself with my changes and I'll update the PR over the next coming days.

2024-01-09 00:30 UTC, dandxy89 commented
Just as an FYI this PR only contains a impl for Traditional. 

```
Traditional <- Adding in this PR
Fibonacci
Woodie
Classic
DM
Camarilla
```

I can follow up with another PR to implement the [remainder](https://www.tradingview.com/support/solutions/43000521824-pivot-points-standard/)

2024-01-11 19:51 UTC, amv-dev commented on src/methods/pivot_point_standard.rs
> +	close: ValueType,
Do we even need internal state? It seems like `PivotPointStandard` may be simple unit struct without internal state.

2024-02-03 06:06 UTC, amv-dev requested changes

2024-02-03 06:06 UTC, amv-dev commented on src/methods/pivot_point_standard.rs
> +pub struct PivotPointStandard {}
Please remove those curly brackets. It's useless.

2024-02-03 06:13 UTC, amv-dev commented
Please make this change and I will merge your PR.

But I think this feature must be refactored in the future. As I see, there is no internal state. On the other hand there are too many values in the output. So I think the whole feature might be created by traits. Something like
```rust
pub trait PivotPointStandard: OHLCV {
  fn pp(&self) -> ValueType {
    (self.high() + self.low() + self.close())/3.0
  }
  ...
}

impl<T: OHLCV> PivotPointStandard for T {}
```

2024-02-03 08:49 UTC, closed without merging

2024-02-03 08:50 UTC, dandxy89 commented
Thanks for the feedback. 

I'll look at the suggestions later this year.